const express = require('express');
const cors = require('cors');
const http = require('http');
const app = express();
const server = http.Server(app);
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => { res.json({ message: 'Dev Radar Backend running successfully!' }); });
const PORT = process.env.LISTEN_PORT || 3333;
server.listen(PORT, () => { console.log('Server is running on port ' + PORT); });
